var netter_data = `{
	    "plates": [
{"number":402 ,
            "name": "Upper Limb: Surface Anatomy",
            "img": "Images/Plate402.png",
            "img_num": "Images/Plate402Num.png",
	        "structures": [
{"number": 1, "name": "Trapezius muscle", "important": 0},
{"number": 2, "name": "Clavicle", "important": 0},
{"number": 3, "name": "Acromion", "important": 0},
{"number": 4, "name": "Deltoid muscle", "important": 0},
{"number": 5, "name": "Deltopectoral grooce", "important": 0},
{"number": 6, "name": "Cephalic vein", "important": 0},
{"number": 7, "name": "Biceps brachii muscle", "important": 0},
{"number": 8, "name": "Cubital fossa", "important": 0},
{"number": 9, "name": "Cephalic vein", "important": 0},
{"number": 10, "name": "Median antebrachial vein", "important": 0},
{"number": 11, "name": "Brachioradialis muscle", "important": 0},
{"number": 12, "name": "Flexor carpi radialis tendon", "important": 0},
{"number": 13, "name": "Thenar eminence", "important": 0},
{"number": 14, "name": "Pectoralis major muscle", "important": 0},
{"number": 15, "name": "Serratus anterior muscle", "important": 0},
{"number": 16, "name": "Triceps brachii muscle (long head)", "important": 0},
{"number": 17, "name": "Basilic vein", "important": 0},
{"number": 18, "name": "Palmaris longus tendon", "important": 0},
{"number": 19, "name": "Flexor digitorum superficial tendons", "important": 0},
{"number": 20, "name": "Flexor carpi ulnaris tendon", "important": 0},
{"number": 21, "name": "Hypothenar eminence", "important": 0},
{"number": 22, "name": "Proximal palmar crease", "important": 0},
{"number": 23, "name": "Deltoid muscle", "important": 0},
{"number": 24, "name": "Triceps brachii muscle (long head)", "important": 0},
{"number": 25, "name": "Triceps brachii muscle (lateral head)", "important": 0},
{"number": 26, "name": "Triceps brachii muscle (tendon)", "important": 0},
{"number": 27, "name": "Brachioradialis and extensor carpi radialis longus muscles", "important": 0},
{"number": 28, "name": "Extensor carpi radialis brevis", "important": 0},
{"number": 29, "name": "Cephalic vein", "important": 0},
{"number": 30, "name": "Anatomical snuffbox", "important": 0},
{"number": 31, "name": "Extensor pollicis longus tendon", "important": 0},
{"number": 32, "name": "Extensor indicis tendon", "important": 0},
{"number": 33, "name": "Olecranon", "important": 0},
{"number": 34, "name": "Flexor carpi ulnaris muscle", "important": 0},
{"number": 35, "name": "Extensor carpi ulnaris muscle", "important": 0},
{"number": 36, "name": "Extensor digitorum tendons", "important": 0},
{"number": 37, "name": "Site of metacarpophalangeal (MCP) join (knucles)", "important": 0},
{"number": 38, "name": "Site of prosimal interphalangeal (PIP) joint", "important": 0},
{"number": 39, "name": "Site of distal interphalangeal (DIP) joint", "important": 0}
]},
{"number": 404,
            "name": "Cutaneous Innervation of Upper Limb",
            "img": "Images/Plate404.png",
            "img_num": "Images/Plate404Num.png",
	        "structures": [
{"number": 1, "name": "Supraclavicular nerves (from cervical plexus C3,4)", "important": 0},
{"number": 2, "name": "Axillary nerve - Superior Lateral brachial cutaneous nerve (C5,6)", "important": 0},
{"number": 3, "name": "Radial nerve - Inferior lateral brachial cutaneous nerve (C5,6)", "important": 0},
{"number": 4, "name": "Lateral antebrachial cutaneous nerve (C5, 6 [7]) from musculocutaneous nerve)", "important": 0},
{"number": 5, "name": "Intercostobrachial nerve (T2) and medial brachial cutaneous nerve (T1)", "important": 0},
{"number": 6, "name": "Medial antebrachial cutaneous nerve (C8, T1)", "important": 0},
{"number": 7, "name": "Ulnar nerve (C8, T1)", "important": 0},
{"number": 8, "name": "Palmar branch", "important": 0},
{"number": 9, "name": "Common and proper palmar digital nerves", "important": 0},
{"number": 10, "name": "Radial nerve - Superficial branch (C6-8)", "important": 0},
{"number": 11, "name": "Median nerve - Palmar branch and common and proper palmar digital nerves (C6-8)", "important": 0},
{"number": 12, "name": "Median nerve - Palmar branch and common and proper palmar digital nerves (C6-8)", "important": 0},
{"number": 13, "name": "Dorsal branch and dorsal digital nerves", "important": 0},
{"number": 14, "name": "Proper palmar digital branches", "important": 0},
{"number": 15, "name": "Supraclavicular nerves - Medial, intermediate and lateral branches (C3,4)", "important": 0},
{"number": 16, "name": "Axillary nerve - Superior lateral brachial cutaneous nerve (C5,6)", "important": 0},
{"number": 17, "name": "Radial nerve - Posterior brachial cutaneous nerve (C5-8)", "important": 0},
{"number": 18, "name": "Radial nerve - Inferior lateral brachial cutaneous nerve", "important": 0},
{"number": 19, "name": "Radial nerve - Posterior antebrachial cutaneous nerve (C[5], 6-8)", "important": 0},
{"number": 20, "name": "Lateral antebrachial cutaenous nerve (C5,6[7]) from musculocutaneous nerve", "important": 0},
{"number": 21, "name": "Radial nerve - Superficial branch and dorsal digital branches (C6-8)", "important": 0},
{"number": 22, "name": "Median nerve - Proper palmar digital nerves", "important": 0}
]},
{"number": 407,
            "name": "Lymph Vessels and Nodes of Upper Limb",
            "img": "Images/Plate407.png",
            "img_num": "Images/Plate407Num.png",
	        "structures": [
{"number": 1, "name": "Intraclavicular node", "important": 0},
{"number": 2, "name": "Lateral axillary (humeral) nodes (along axillary vein)", "important": 1},
{"number": 3, "name": "Cephalic vein", "important": 1},
{"number": 4, "name": "Basilic vein", "important": 1},
{"number": 5, "name": "Supratrochlear nodes", "important": 0},
{"number": 6, "name": "Median cubital vein", "important": 0},
{"number": 7, "name": "Cephalic vein", "important": 1},
{"number": 8, "name": "Basilic vein", "important": 1},
{"number": 9, "name": "Vessels passing to dorsum of hand", "important": 0},
{"number": 10, "name": "Vessels passing to dorsum of hand", "important": 0},
{"number": 11, "name": "Vessels passing around interdigital space to dorsum of hand", "important": 0},
{"number": 12, "name": "Vessels passing to dorsum of fingers", "important": 0}
]},
            {"number": 421,
            "name": "Muscles of Arm: Anterior Views",
            "img": "Images/Plate421.png",
            "img_num": "Images/Plate421Num.png",
	        "structures": [
                {"number": 1, "name": "Coracoacromial ligament", "important": 0},
                {"number": 2, "name": "Subacromial bursa", "important": 0},
                {"number": 3, "name": "Greater tubercle of humerus", "important": 0},
                {"number": 4, "name": "Lesser tubercle of humerus", "important": 0},
                {"number": 5, "name": "Intertubercular tendon sheath", "important": 0},
                {"number": 6, "name": "Deltoid muscle (reflected)", "important": 0},
                {"number": 7, "name": "Pectoralis major muscle (reflected)", "important": 0},
                {"number": 8, "name": "Anterior circumflex humeral artery", "important": 0},
                {"number": 9, "name": "Biceps brachii muscle (Long head)", "important": 0},
                {"number": 10, "name": "Biceps Brachii muscle (Short head)", "important": 0},
                {"number": 11, "name": "Brachial artery (cut)", "important": 0},
                {"number": 12, "name": "Median nerve (cut)", "important": 0},
                {"number": 13, "name": "Brachialis muscle", "important": 0},
                {"number": 14, "name": "Lateral antebrachial cutaneous nerve", "important": 0},
                {"number": 15, "name": "Bicipital aponeurosis", "important": 0},
                {"number": 16, "name": "Biceps brachii tendon", "important": 0},
                {"number": 17, "name": "Brachioradialis muscle", "important": 0},
                {"number": 18, "name": "Pronator teres muscle", "important": 0},
                {"number": 19, "name": "Flexor carpi radialis muscle", "important": 0},
                {"number": 20, "name": "Acromion", "important": 0},
                {"number": 21, "name": "Coracoid process", "important": 0},
                {"number": 22, "name": "Pectoralis minor tendon (cut)", "important": 0},
                {"number": 23, "name": "Subscapularis muscle", "important": 0},
                {"number": 24, "name": "Musculocutaneous nerve (cut)", "important": 0},
                {"number": 25, "name": "Coracobrachialis muscle", "important": 0},
                {"number": 26, "name": "Circumflex scapular artery (cut)", "important": 0},
                {"number": 27, "name": "Teres major muscle", "important": 0},
                {"number": 28, "name": "Latissimus dorsi muscle", "important": 0},
                {"number": 29, "name": "Biceps Brachii tendon (Long head cut)", "important": 0},
                {"number": 30, "name": "Biceps Brachii tendon (Short head cut)", "important": 0},
                {"number": 31, "name": "Coracobrachialis muscle", "important": 0},
                {"number": 32, "name": "Musculocutaneous nerve", "important": 0},
                {"number": 33, "name": "Deltoid muscle (cut)", "important": 0},
                {"number": 34, "name": "Lateral intermuscular septum", "important": 0},
                {"number": 35, "name": "Lateral epicondyle of humerus", "important": 0},
                {"number": 36, "name": "Lateral antebrachial cutaneous nerve", "important": 0},
                {"number": 37, "name": "Head of radius", "important": 0},
                {"number": 38, "name": "Biceps brachii tendon", "important": 0},
                {"number": 39, "name": "Radial tuberosity", "important": 0},
                {"number": 40, "name": "Brachialis muscle", "important": 0},
                {"number": 41, "name": "Medial intermuscular septum", "important": 0},
                {"number": 42, "name": "Medial epicondyle of humerus", "important": 0},
                {"number": 43, "name": "Ulnar tuberosity", "important": 0}
]},
            {"number": 422,
            "name": "Muscles of Arm: Posterior Views",
            "img": "Images/Plate422.png",
            "img_num": "Images/Plate422Num.png",
	        "structures": [
                {"number": 1, "name": "Teres major muscle", "important": 0},
                {"number": 2, "name": "Posterior brachial cutaneous nerve (from radial nerve)", "important": 0},
                {"number": 3, "name": "Medial intermuscular septum", "important": 0},
                {"number": 4, "name": "Ulnar nerve", "important": 0},
                {"number": 5, "name": "Medial epicondyle of humerus", "important": 0},
                {"number": 6, "name": "Olecranon of ulna", "important": 0},
                {"number": 7, "name": "Flexor carpi ulnaris muscle", "important": 0},
                {"number": 8, "name": "Aconeus muscle", "important": 0},
                {"number": 9, "name": "Extensor carpi radialis longus muscle", "important": 0},
                {"number": 10, "name": "Extensor carpi ulnaris muscle", "important": 0},
                {"number": 11, "name": "Posterior antebrachial cutaneous nerve (from radial nerve)", "important": 0},
                {"number": 12, "name": "Extensor digitorum muscle", "important": 0},
                {"number": 13, "name": "Extensor carpi radialis brevs muscle", "important": 0},
                {"number": 14, "name": "Supraspinatus muscle", "important": 0},
                {"number": 15, "name": "Infraspinatus muscle", "important": 0},
                {"number": 16, "name": "Teres minor muscle", "important": 0},
                {"number": 17, "name": "Axillary nerve and posterior circumflex humeral artery", "important": 0},
                {"number": 18, "name": "Deltoid muscle (cut and reflected)", "important": 0},
                {"number": 19, "name": "Superior lateral brachial cutaneous nerve", "important": 0},
                {"number": 20, "name": "Triceps brachii muscle (Long head)", "important": 0},
                {"number": 21, "name": "Triceps brachii muscle (Lateral head)", "important": 0},
                {"number": 22, "name": "Triceps brachii muscle tendon", "important": 0},
                {"number": 23, "name": "Brachioradialis muscle", "important": 0},
                {"number": 24, "name": "Teres major muscle and tendon", "important": 0},
                {"number": 25, "name": "Triceps brachii muscle (Long head)", "important": 0},
                {"number": 26, "name": "Triceps brachii muscle (Lateral head)", "important": 0},
                {"number": 27, "name": "Triceps brachii muscle (Medial head)", "important": 0},
                {"number": 28, "name": "Medial epicondyle of humerus", "important": 0},
                {"number": 29, "name": "Ulnar nerve", "important": 0},
                {"number": 30, "name": "Olecranon of ulna", "important": 0},
                {"number": 31, "name": "Anconeus muscle", "important": 0},
                {"number": 32, "name": "Capsule of glenohumeral joint", "important": 0},
                {"number": 33, "name": "Supraspinatus tendon", "important": 0},
                {"number": 34, "name": "Infraspinatus  tendon (cut)", "important": 0},
                {"number": 35, "name": "Teres minor tendon (cut)", "important": 0},
                {"number": 36, "name": "Axillary nerve", "important": 0},
                {"number": 37, "name": "Posterior circumflex humeral artery", "important": 0},
                {"number": 38, "name": "Superior lateral brachial cutaneous nerve", "important": 0},
                {"number": 39, "name": "Profunda brachii (deep brachial) artery", "important": 0},
                {"number": 40, "name": "Radial nerve", "important": 0},
                {"number": 41, "name": "Middle collateral artery", "important": 0},
                {"number": 42, "name": "Inferior lateral brachial cutaneous nerve", "important": 0},
                {"number": 43, "name": "Lateral intermuscular septum", "important": 0},
                {"number": 44, "name": "Radial nerve branch to aconeus muscle and medial head of triceps brachii muscle", "important": 0},
                {"number": 45, "name": "Posterior antebrachial cutaneous nerve", "important": 0},
                {"number": 46, "name": "Lateral epicondyle of humerus", "important": 0}
]},
{"number":424 ,
            "name": "Arteries of Arm and Proximal Forearm",
            "img": "Images/Plate424.png",
            "img_num": "Images/Plate424Num.png",
	        "structures": [
{"number": 1, "name": "Pectoral branch", "important": 0},
{"number": 2, "name": "Clavicular branch", "important": 0},
{"number": 3, "name": "Acromial branch", "important": 0},
{"number": 4, "name": "Deltoid branch", "important": 0},
{"number": 5, "name": "Thoracoacromial artery", "important": 0},
{"number": 6, "name": "Axillary artery", "important": 1},
{"number": 7, "name": "Anterior circumflex humeral artery", "important": 0},
{"number": 8, "name": "Posterior circumflex humeral artery", "important": 0},
{"number": 9, "name": "Brachial artery", "important": 1},
{"number": 10, "name": "Profunda brachii (deep brachial) artery", "important": 0},
{"number": 11, "name": "Radial collateral artery", "important": 0},
{"number": 12, "name": "Middle collateral artery", "important": 0},
{"number": 13, "name": "Radial recurrent artery", "important": 0},
{"number": 14, "name": "Recurrent interosseous artery", "important": 0},
{"number": 15, "name": "Posterior interosseous artery", "important": 0},
{"number": 16, "name": "Radial artery", "important": 1},
{"number": 17, "name": "Superficial palmar branch of radial artery", "important": 0},
{"number": 18, "name": "Deep palmar arch", "important": 0},
{"number": 19, "name": "Princeps pollicis artery", "important": 0},
{"number": 20, "name": "Radialis indicis artery", "important": 0},
{"number": 21, "name": "Superficial palmar arch", "important": 0},
{"number": 22, "name": "Superior thoracic artery", "important": 0},
{"number": 23, "name": "Lateral thoracic artery", "important": 0},
{"number": 24, "name": "Subscapular artery", "important": 0},
{"number": 25, "name": "Circumflex scapular artery", "important": 0},
{"number": 26, "name": "Thoracodorsal artery", "important": 0},
{"number": 27, "name": "Level of lower margin of teres major muscle (landmark for name change from axillary to brachial artery)", "important": 0},
{"number": 28, "name": "Superior ulnar collateral artery", "important": 0},
{"number": 29, "name": "Inferior ulnar collateral artery", "important": 0},
{"number": 30, "name": "Anterior ulnar recurrent artery", "important": 0},
{"number": 31, "name": "Posterior ulnar recurrent artery", "important": 0},
{"number": 32, "name": "Common interosseous artery", "important": 0},
{"number": 33, "name": "Anterior interosseous artery", "important": 0},
{"number": 34, "name": "Ulnar artery", "important": 1},
{"number": 35, "name": "Dorsal carpal artery", "important": 0},
{"number": 36, "name": "Deep palmar branch of ulnar artery", "important": 0},
{"number": 37, "name": "Palmar metacarpal arteries", "important": 0},
{"number": 38, "name": "Palmar digital atery", "important": 0},
{"number": 39, "name": "Common palmar digital arteries", "important": 0},
{"number": 40, "name": "Proper palmar digital arteries", "important": 0}
]},
            {"number": 500,
            "name": "Knee: Cruciate and Collateral Ligaments",
            "img": "Images/Plate500.png",
            "img_num":"Images/Plate500Num.png",
	        "structures":[
{"number": 1, "name": "Anterior cruciate ligament", "important": 0},
{"number": 2, "name": "Lateral condyle of femur (articular surface)", "important": 0},
{"number": 3, "name": "Popliteus tendon", "important": 0},
{"number": 4, "name": "Fibular collateral ligament", "important": 0},
{"number": 5, "name": "Lateral meniscus", "important": 0},
{"number": 6, "name": "Transverse ligament of knee", "important": 0},
{"number": 7, "name": "Head of fibula", "important": 0},
{"number": 8, "name": "Tubercle of iliotibial tract (Gerdy's tubercle)", "important": 0},
{"number": 9, "name": "Posterior cruciate ligament", "important": 0},
{"number": 10, "name": "Medial condyle of femur (articular surface)", "important": 0},
{"number": 11, "name": "Medial meniscus", "important": 0},
{"number": 12, "name": "Tibial collateral ligament (superficial and deep fibers", "important": 0},
{"number": 13, "name": "Medial condyle of tibia", "important": 0},
{"number": 14, "name": "Tibial tuberosity", "important": 0},
{"number": 15, "name": "Adductor tubercle on medial condyle of femur", "important": 0},
{"number": 16, "name": "Medial condyle of femur (articular surface)", "important": 0},
{"number": 17, "name": "Tibial collateral ligament (superficial and deep fibers)", "important": 0},
{"number": 18, "name": "Medial meniscus", "important": 0},
{"number": 19, "name": "Medial condyle of tibia", "important": 0},
{"number": 20, "name": "Posterior cruciate ligament", "important": 0},
{"number": 21, "name": "Anterior cruciate ligament", "important": 0},
{"number": 22, "name": "Posterior meniscofemoral ligament", "important": 0},
{"number": 23, "name": "Lateral condyle of femur (articular surface)", "important": 0},
{"number": 24, "name": "Popliteus tendon", "important": 0},
{"number": 25, "name": "Fibular collateral ligament", "important": 0},
{"number": 26, "name": "Lateral meniscus", "important": 0},
{"number": 27, "name": "Head of fibula", "important": 0}
            ]},
            {"number": 501,
            "name": "Knee: Anteroposterior Radiograph and Posterior View",
            "img": "Images/Plate501.png",
            "img_num": "Images/Plate501Num.png",
	        "structures": [
{"number": 1, "name": "Medial femoral condyle", "important": 0},
{"number": 2, "name": "Intercondylar eminence", "important": 0},
{"number": 3, "name": "Tibial plateau", "important": 0},
{"number": 4, "name": "Femur", "important": 0},
{"number": 5, "name": "Lateral femoral condyle", "important": 0},
{"number": 6, "name": "Tibial plateau", "important": 0},
{"number": 7, "name": "Fibula", "important": 0},
{"number": 8, "name": "Tibia", "important": 0},
{"number": 9, "name": "Semitendinosus muscle", "important": 0},
{"number": 10, "name": "Sartorius muscle", "important": 0},
{"number": 11, "name": "Semimembranosus muscle", "important": 0},
{"number": 12, "name": "Gracilis muscle", "important": 0},
{"number": 13, "name": "Medial head of gastrocnemius muscle (cut)", "important": 0},
{"number": 14, "name": "Medial subtendinous bursa of gastrocnemius muscle (open)", "important": 0},
{"number": 15, "name": "Oblique popliteal ligament", "important": 0},
{"number": 16, "name": "Tibial collateral ligament", "important": 0},
{"number": 17, "name": "Bursa of semimembranosus muscle", "important": 0},
{"number": 18, "name": "Semimembranosus tendon", "important": 0},
{"number": 19, "name": "Interosseous membrane", "important": 0},
{"number": 20, "name": "Tibia", "important": 0},
{"number": 21, "name": "Plantaris muscle (cut)", "important": 0},
{"number": 22, "name": "Iliotibial tract", "important": 0},
{"number": 23, "name": "Biceps femoris muscle", "important": 0},
{"number": 24, "name": "Lateral head of gastrocnemius muscle (cut and reflect superiorly and laterally", "important": 0},
{"number": 25, "name": "Lateral subtendinous bursa of gastrocnemius muscle", "important": 0},
{"number": 26, "name": "Fibular collateral ligament", "important": 0},
{"number": 27, "name": "Arcuate popliteal ligament", "important": 0},
{"number": 28, "name": "Biceps femoris tendon", "important": 0},
{"number": 29, "name": "Common fibular nerve", "important": 0},
{"number": 30, "name": "Popliteus muscle", "important": 0},
{"number": 31, "name": "Fibula", "important": 0}
            ]},
            {"number": 502,
            "name": "Knee: Posterior and Sagittal Views",
            "img": "Images/Plate502.png",
            "img_num": "Images/Plate502Num.png",
	        "structures": [
{"number": 1, "name": "Adductor magnus tendon", "important": 0},
{"number": 2, "name": "Medial head of gastrocnemius muscle", "important": 0},
{"number": 3, "name": "Subtendinous bursa", "important": 0},
{"number": 4, "name": "Tibial collateral ligament", "important": 0},
{"number": 5, "name": "Semimembranosus tendon", "important": 0},
{"number": 6, "name": "Oblique popliteal ligament (tendinous expansion of semimembranosus muscle)", "important": 0},
{"number": 7, "name": "Semimembranosus bursa deep to tendon", "important": 0},
{"number": 8, "name": "Popliteus muscle", "important": 0},
{"number": 9, "name": "Femur (popliteal surface)", "important": 0},
{"number": 10, "name": "Attachement of joint capsule", "important": 0},
{"number": 11, "name": "Plantaris muscle", "important": 0},
{"number": 12, "name": "Lateral head of gastrocnemius muscle", "important": 0},
{"number": 13, "name": "Subtendinous bursa", "important": 0},
{"number": 14, "name": "Fibular collatoral ligament", "important": 0},
{"number": 15, "name": "Subtendinous bursa", "important": 0},
{"number": 16, "name": "Biceps femoris tendon", "important": 0},
{"number": 17, "name": "Subtendinous bursa", "important": 0},
{"number": 18, "name": "Arcuate popliteal ligament (edge of capsule that arches over popliteus muscle)", "important": 0},
{"number": 19, "name": "Head of fibula", "important": 0},
{"number": 20, "name": "Posterior ligament of fibular head", "important": 0},
{"number": 21, "name": "Attachment of joint capsule", "important": 0},
{"number": 22, "name": "Interosseous membrane", "important": 0},
{"number": 23, "name": "Tibia", "important": 0},
{"number": 24, "name": "Lateral subtendious bursa of gastrocnemius muscle", "important": 0},
{"number": 25, "name": "Synovial membrane", "important": 0},
{"number": 26, "name": "Articular cartilages", "important": 0},
{"number": 27, "name": "Tibia", "important": 0},
{"number": 28, "name": "Femur", "important": 0},
{"number": 29, "name": "Articularis genu muscle", "important": 0},
{"number": 30, "name": "Quadriceps femoris tendon", "important": 0},
{"number": 31, "name": "Suprapatellar fat body", "important": 0},
{"number": 32, "name": "Suprapatellar (synovial) bursa", "important": 0},
{"number": 33, "name": "Patella", "important": 0},
{"number": 34, "name": "Subcutaneous prepatellar bursa", "important": 0},
{"number": 35, "name": "Articular cavity", "important": 0},
{"number": 36, "name": "Synovial membrane", "important": 0},
{"number": 37, "name": "Patellar ligament", "important": 0},
{"number": 38, "name": "Infrapatellar fat pad", "important": 0},
{"number": 39, "name": "Subcutaneous infrapatellar bursa", "important": 0},
{"number": 40, "name": "Deep (subtendinous) infrapatellar bursa", "important": 0},
{"number": 41, "name": "Lateral muniscus", "important": 0},
{"number": 42, "name": "Tibial tuberosity", "important": 0}
            ]},
            {"number": 503,
            "name": "Arteries of Lower Limb: Schema",
            "img": "Images/Plate503.png",
            "img_num": "Images/Plate503Num.png",
	        "structures": [
{"number": 1, "name": "Deep circumflex iliac artery", "important": 0},
{"number": 2, "name": "Superficial circumflex iliac artery", "important": 0},
{"number": 3, "name": "Femoral artery", "important": 0},
{"number": 4, "name": "Lateral circumflex femoral artery (Ascending branch)", "important": 0},
{"number": 5, "name": "Lateral circumflex femoral artery (Transverse branch)", "important": 0},
{"number": 6, "name": "Lateral circumflex femoral artery (Descending branch)", "important": 0},
{"number": 7, "name": "Lateral circumflex femoral artery", "important": 0},
{"number": 8, "name": "Profunda femoris (deep femoral) artery", "important": 0},
{"number": 9, "name": "Perforating branches", "important": 0},
{"number": 10, "name": "Femoral artery passing through adductor hiatus within adductor magnus muscle", "important": 0},
{"number": 11, "name": "Superior lateral genicular artery", "important": 0},
{"number": 12, "name": "Patellar anastomosis", "important": 0},
{"number": 13, "name": "Inferior lateral genicular artery", "important": 0},
{"number": 14, "name": "Posterior tibial recurrent artery", "important": 0},
{"number": 15, "name": "Circumflex fibular branch", "important": 0},
{"number": 16, "name": "Anterior tibial artery", "important": 0},
{"number": 17, "name": "Interosseous membrane", "important": 0},
{"number": 18, "name": "Fibular artery", "important": 0},
{"number": 19, "name": "Perforating branch", "important": 0},
{"number": 20, "name": "Anterior lateral malleolar artery", "important": 0},
{"number": 21, "name": "Lateral tarsal artery", "important": 0},
{"number": 22, "name": "Posterior perforating branch", "important": 0},
{"number": 23, "name": "Plantar arch", "important": 0},
{"number": 24, "name": "External iliac artery", "important": 0},
{"number": 25, "name": "Inferior epigastric artery", "important": 0},
{"number": 26, "name": "Superficial epigastric artery", "important": 0},
{"number": 27, "name": "Superficial external pudental artery", "important": 0},
{"number": 28, "name": "Obturator artery", "important": 0},
{"number": 29, "name": "Deep external pudental artery", "important": 0},
{"number": 30, "name": "Medial circumflex femoral artery", "important": 0},
{"number": 31, "name": "Femoral artery", "important": 0},
{"number": 32, "name": "Muscular branches", "important": 0},
{"number": 33, "name": "Descending genicular artery", "important": 0},
{"number": 34, "name": "Articular branch", "important": 0},
{"number": 35, "name": "Saphenous branch", "important": 0},
{"number": 36, "name": "Superior medial genicular artery", "important": 0},
{"number": 37, "name": "Popliteal artery", "important": 0},
{"number": 38, "name": "Middle genicular artery", "important": 0},
{"number": 39, "name": "Inferior medial genicular artery", "important": 0},
{"number": 40, "name": "Anterior tibial recurrent artery", "important": 0},
{"number": 41, "name": "Posterior tibial artery", "important": 0},
{"number": 42, "name": "Fibular artery", "important": 0},
{"number": 43, "name": "Anterior tibial artery", "important": 0},
{"number": 44, "name": "Anterior medial malleolar artery", "important": 0},
{"number": 45, "name": "Medial tarsal artery", "important": 0},
{"number": 46, "name": "Arcuate artery", "important": 0},
{"number": 47, "name": "Dorsalis pedis artery", "important": 0},
{"number": 48, "name": "Deep plantar artery", "important": 0},
{"number": 49, "name": "Dorsal digital arteries", "important": 0}
]}

    ]}`;


var myObj = JSON.parse(netter_data);

for (var i = 0; i < myObj.plates.length; i++) {
    var temp_name = [];
    for(var ii = 0; ii < myObj.plates[i].structures.length; ii++) {
        temp_name[ii] = myObj.plates[i].structures[ii].name;
    }
    temp_name.sort();
    myObj.plates[i].structures_sort_name = temp_name;
}

/*
{"number": ,
            "name": "",
            "img": "Images/Plate500.png",
            "img_num": "Images/Plate500Num.png",
	        "structures": [
{"number": 1, "name": "", "important": 0},
{"number": 2, "name": "", "important": 0},
{"number": 3, "name": "", "important": 0},
{"number": 4, "name": "", "important": 0},
{"number": 5, "name": "", "important": 0},
{"number": 6, "name": "", "important": 0},
{"number": 7, "name": "", "important": 0},
{"number": 8, "name": "", "important": 0},
{"number": 9, "name": "", "important": 0},
{"number": 10, "name": "", "important": 0},
{"number": 11, "name": "", "important": 0},
{"number": 12, "name": "", "important": 0},
{"number": 13, "name": "", "important": 0},
{"number": 14, "name": "", "important": 0},
{"number": 15, "name": "", "important": 0},
{"number": 16, "name": "", "important": 0},
{"number": 17, "name": "", "important": 0},
{"number": 18, "name": "", "important": 0},
{"number": 19, "name": "", "important": 0},
{"number": 20, "name": "", "important": 0},
{"number": 21, "name": "", "important": 0},
{"number": 22, "name": "", "important": 0},
{"number": 23, "name": "", "important": 0},
{"number": 24, "name": "", "important": 0},
{"number": 25, "name": "", "important": 0},
{"number": 26, "name": "", "important": 0},
{"number": 27, "name": "", "important": 0},
{"number": 28, "name": "", "important": 0},
{"number": 29, "name": "", "important": 0},
{"number": 30, "name": "", "important": 0},
{"number": 31, "name": "", "important": 0},
{"number": 32, "name": "", "important": 0},
{"number": 33, "name": "", "important": 0},
{"number": 34, "name": "", "important": 0},
{"number": 35, "name": "", "important": 0},
{"number": 36, "name": "", "important": 0},
{"number": 37, "name": "", "important": 0},
{"number": 38, "name": "", "important": 0},
{"number": 39, "name": "", "important": 0},
{"number": 40, "name": "", "important": 0},
{"number": 41, "name": "", "important": 0},
{"number": 42, "name": "", "important": 0},
{"number": 43, "name": "", "important": 0},
{"number": 44, "name": "", "important": 0},
{"number": 45, "name": "", "important": 0},
{"number": 46, "name": "", "important": 0},
{"number": 47, "name": "", "important": 0},
{"number": 48, "name": "", "important": 0},
{"number": 49, "name": "", "important": 0},
{"number": 50, "name": "", "important": 0},
]},

*/